# version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mars-rover-app
    restart: unless-stopped
    working_dir: /var/www/src
    volumes:
      - ./src:/var/www/src
    networks:
      - mars-rover-network

  nginx:
    image: nginx:alpine
    container_name: mars-rover-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - mars-rover-network

  db:
    image: mysql:8.0
    container_name: mars-rover-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./lib/mysql:/var/lib/mysql
    networks:
      - mars-rover-network

networks:
  mars-rover-network:
    driver: bridge

volumes:
  mysql_data: {}